# Generated by Django 4.1.7 on 2023-06-01 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cusname', models.CharField(max_length=50)),
                ('hotlname', models.CharField(max_length=50)),
                ('date', models.DateField()),
            ],
        ),
    ]
