# Generated by Django 4.1.7 on 2023-06-01 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0002_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='number',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
